project_id = "ipabmyxckmlvxffkypro"

[functions.get-message]
verify_jwt = true

[functions.get-credits]
verify_jwt = true

[functions.admin-credits]
verify_jwt = true

[functions.create-multibanco-payment]
verify_jwt = true

[functions.check-payment-status]
verify_jwt = true

[functions.ifthenpay-callback]
verify_jwt = false

[functions.grant-welcome-credit]
verify_jwt = true

[functions.list-reveals]
verify_jwt = true

[functions.get-daily-message]
verify_jwt = true

[functions.admin-list-users]
verify_jwt = true
