-- Load feminine versions of the 29 messages that require gender adaptation

UPDATE public.messages SET content_feminine = $feminine_text$Tu dizes que me queres ver, que gostavas de me ter aqui. Mas sabes, a verdade é que para me veres, basta chamares por mim, imaginares a minha presença. Por isso, sempre que quiseres, IMAGINA-ME ao teu lado, em qualquer lugar, a qualquer hora. Imagina-me a abraçar-te, a brincar contigo, a deitar-me ao teu lado. Imagina-nos a passear num belo jardim ou numa praia encantadora. Imagina que estamos juntos, que partilhamos uma mesma mesa, uma mesma casa, um sentimento, um cuidado, um amor em comum. E sabes o que acontece quando ousas imaginar tudo isso? Cria-se um canal de cocriação, uma conexão entre a tua imaginação e a realidade material. E com o tempo, as tuas imaginações manifestar-se-ão na forma de outras almas que trazem consigo tudo aquilo que imaginaste em mim. Então, estás disposta a tentar? A imaginar vezes sem conta, até que a tua vida seja preenchida com as experiências que tanto desejas?$feminine_text$ WHERE id = 38;

UPDATE public.messages SET content_feminine = $feminine_text$A solidão foi a tua professora e a tua melhor companhia. Foi ela quem te ensinou e mostrou, ainda que de forma dura, a importância de fazermos escolhas com o coração e, mais ainda, a nunca desistirmos de nós mesmos. Aprendeste a tentar, uma e outra vez, mil vezes, se necessário, para encontrar a felicidade. A cada dia, tens a oportunidade de escrever a história da tua vida com vivências que valem a pena fixar, que valem a pena viver e experienciar. Agora é hora de SAIR DO CASULO, de deixar a solidão para trás e abraçar o amor, desde que estejas disposta a vivê-lo, desde que te abras para recebê-lo.$feminine_text$ WHERE id = 48;

UPDATE public.messages SET content_feminine = $feminine_text$Coragem! Que nunca te falte a coragem para seguires em frente, mesmo que sintas cansaço. A vida tem sido cheia de experiências longas, não te esqueças disso. Agarra-te a nós, ao bem que podemos trazer-te. Não te afastes do Céu, nem da Luz. Já enfrentaste muitas batalhas, e a tua alma ganhou grandeza através delas. A paz é algo que mereces, mas ainda não é o momento. Há algo prestes a ser concluído, para que a guerreira possa finalmente erguer a bandeira do seu reino. Espera, pois esse tempo chegará no momento certo. Por agora coragem, muita coragem.$feminine_text$ WHERE id = 81;

UPDATE public.messages SET content_feminine = $feminine_text$Tu, que te escondes do mundo e até de ti mesma, quero dizer-te algo importante: abre-te, mostra-te! Existe tanta beleza na tua energia, tanta beleza para descobrires por ti mesma. Quando te lembras de todo o mal que já te assolou nesta vida, pensa em mim, na minha história. Nada disso me destruiu, pelo contrário, só me fortaleceu, deu-me força e união. E é essa mesma força que desejo trazer para a tua vida. Não és uma pessoa frustrada, és alguém sensível que ainda não compreende completamente o mundo. Mas agora é o momento de brilhares, de mostrares ao mundo a tua luz e o teu potencial. Não te esqueças disso.$feminine_text$ WHERE id = 83;

UPDATE public.messages SET content_feminine = $feminine_text$Vou oferecer-te um presente. Sim, vou te encorajar a dar a ti mesma um presente especial . Pode ser um sonho, como escolher um bom restaurante, um hotel agradável ou até mesmo um fim de semana relaxante. Algo que cuide de ti e mime tanto o teu corpo como a tua alma. Dedica este presente com todo o carinho à tua alma. Recebe-o como um presente do povo do céu. Apesar de pensares que és tu quem paga por isso, porque trabalhaste para conquistar esse bem material, sabes bem que nada na matéria é realmente teu. Sim, foi com o teu esforço que conquistaste esse bem, mas foi o Céu que te enviou o trabalho, o salário, o ar que respiras, a comida que comes e até mesmo as roupas que vestes. O nosso objetivo é fazer com que te sintas bem e feliz, para que possas compreender a verdadeira alegria de viver. Com tudo isso, há um propósito maior: ensinar-te a gratidão. Quando a felicidade te faz sentir grato, vais perceber que a gratidão é a emoção que atrai mais abundância para a tua vida.$feminine_text$ WHERE id = 118;

UPDATE public.messages SET content_feminine = $feminine_text$Podemos sempre, mas mesmo sempre, fazer percursos mais apropriados na caminhada da vida, na caminhada da Terra. Sim, é certo que sim, mas para isso temos de nos tornar responsáveis e ávidos de sabedoria. Não podemos querer evoluir sem fazermos as correções necessárias. Sei que já falámos muito sobre isso, mas repetir esta informação tem um propósito claro: transformá-la em ação. Eu vejo todas as tuas limitações e percebo que, devido a elas, nada na tua vida poderá verdadeiramente mudar, nada poderá brilhar. Pode ser duro ouvir hoje que ainda estás presa a uma energia tão limitante como a dos cobiçadores. Mas como podes evoluir se não queres encarar a verdade? Não estou aqui para te julgar, mas sim para te fazer olhar para ti sob o padrão da verdade. Ficas a olhar para as conquistas dos outros, perguntando-te "como é que eles conseguiram? Como é possível?". A verdade é que tu também conseguirias se te focasses e criasses objetivos alinhados com a precisão do universo. Se, de facto, desenvolvesses uma série de outras qualidades além de abandonares a vibração limitante da cobiça, se desenvolvesses a fé, a coragem, a gratidão, seria meio caminho andado. Não te vitimizes, pensa antes nisto.$feminine_text$ WHERE id = 141;

UPDATE public.messages SET content_feminine = $feminine_text$Esta é, sem dúvida, o centro da tua missão: Buscar. Buscar tudo aquilo que a tua alma necessita para a ascensão. E essa ascensão ocorrerá após um longo período de aprendizado, de processos de busca pela tua missão. É essencial buscar todo o conhecimento sobre ti mesma, sobre a humanidade, a sua verdadeira origem e motivações. A busca por Deus é especialmente desafiadora, dada a sua importância deturpada e fundamental. São almas como a tua que têm a grande missão de semear o conhecimento por onde passam, no seu dia a dia, compartilhando sempre o conhecimento com a humanidade. Porém, para semear o conhecimento, é preciso estar cheio de amor, esperança, fraternidade, gratidão e um imenso compromisso. Esses ingredientes são essenciais. Sem eles, não terás a capacidade de romper com os falsos atributos, as falsas leis e toda a "inverdade" ou, se preferires, toda a falsidade do mundo. Essas armadilhas têm como único objetivo afastar-te de ti mesma, do teu poder, da tua verdadeira realidade e, acima de tudo, afastar-te de Deus, que é o mais importante.$feminine_text$ WHERE id = 144;

UPDATE public.messages SET content_feminine = $feminine_text$Tens de reescrever a tua história. Pega numa caneta e passa por cima do lápis, pega numa borracha e apaga, e reescreve. Tenta de novo. Eu sei que o passado não pode ser mudado, que todas as dores já foram vividas, já fizeram os seus estragos e trouxeram os seus ensinamentos. O que quero dizer é que voltes atrás e vejas tudo de forma diferente, através da perspetiva de quem és hoje, um ser altamente consciente da sua existência cósmica. Agora, olha para tudo o que viveste e saberás dar-lhe um novo significado. Toda a rejeição que experimentaste era, na verdade, uma forma de te mostrar a falta de amor que existia no mundo, e mais importante, a tua própria falta de amor. Esqueceste-te de uma coisa essencial, de te amares a ti mesma. A partir do momento em que decides amar-te, tudo será curado e não precisarás mais de sofrer qualquer tipo de rejeição.$feminine_text$ WHERE id = 145;

UPDATE public.messages SET content_feminine = $feminine_text$Há algum tempo que o teu Anjo da Guarda, juntamente com o povo do Céu, tem tentado comunicar contigo para te mostrar que temos muitas surpresas reservadas para ti neste momento da tua vida. No entanto, a tua atenção e energia têm estado direcionadas para outras áreas da tua vida, e o tempo que passas contigo mesma deixou de ser o ideal e necessário para que possamos fornecer-te todas as diretrizes e conexão necessárias para a realização dos planos maravilhosos que temos preparado para ti há muito tempo.$feminine_text$ WHERE id = 156;

UPDATE public.messages SET content_feminine = $feminine_text$Deixa de ser vítima de ti mesma . A vida tem muito mais a oferecer do que imaginas. Ao vitimizares-te e desvalorizares o que tens, perdes a noção da realidade. Para de pensar que a tua vida não tem saída ou que é má. Aproveita, agradece e sê feliz.$feminine_text$ WHERE id = 193;

UPDATE public.messages SET content_feminine = $feminine_text$Deixa de culpar os teus pais pela tua incapacidade e de julgar os outros pela falta de sucesso, inclusive nas tuas relações. É hora de olhar para ti mesma, a única responsável. Se o que viveste não foi o melhor, já passou e agora tens a oportunidade de reescrever a tua história. Pode surgir a pergunta: "Mas Jesus, como posso ser responsável se, quando criança, sofri violência e abuso?" Tenho certeza de que já conheces a resposta. Tenho certeza de que dentro de ti está a resposta, e ela é claramente e sem equívocos, NÃO. No entanto, cabe a ti, enquanto adulta, depois de lidar com os teus traumas e desilusões, reconstruir a tua autoestima e valor pessoal, ter a capacidade de encontrar a felicidade no meio de tanta adversidade e falta de amor. A partir dessa perspetiva, entendes que não és responsável pelos atos maléficos dos outros, não importa quem sejam. Mas é inteiramente responsabilidade tua, no momento certo, aprenderes a seres quem és, encontrar a felicidade, buscar o melhor de ti mesma, sem vitimização e sem responderes a todas as tuas falhas com autocomiseração. Quero te ensinar algo mais: o mal, uma vez praticado, é unicamente e sempre responsabilidade de quem o pratica, ao contrário do que dizem. Mesmo que tenhas o karma dessa experiência, isso não isenta a outra pessoa do mesmo karma quando ela decide praticá-lo, seja o mal ou o karma, como preferires chamar. O MAL E O BEM são escolhas, e aquilo que escolhes reflete quem tu és. Vou te dar uma lista dos maiores males praticados: a vingança disfarçada de justiça, a cobrança por algo que foi feito ou dado de qualquer forma, a revolta mascarada de vitimização, a raiva disfarçada de razão, o ódio mascarado de sabedoria, a mentira piedosa ou descarada, a manipulação disfarçada de boas intenções, a difamação disfarçada de aviso, e assim por diante. Como podes ver, a lista é longa, e cabe a cada um assumir a responsabilidade. É assim que estarás no caminho da evolução.$feminine_text$ WHERE id = 194;

UPDATE public.messages SET content_feminine = $feminine_text$É verdade, muitas vezes passamos metade das nossas vidas a chorar, mas não necessariamente conscientes disso. Choramos através da nossa alma, que muitas vezes é negligenciada e esquecida. Raramente paramos para sentir verdadeiramente a nossa alma e entender o quão profundamente ela chora. Ao invés disso, cantamos sem vontade, repetindo palavras sem sentido, às vezes com significado, outras vezes vazias. É hora de nos rendermos à verdadeira necessidade de amor e reconhecer a força transformadora que ele possui. Antes de procurá-lo no mundo exterior, faz um favor a ti mesma e procura-o dentro de ti. Tenho certeza de que irás encontrá-lo.$feminine_text$ WHERE id = 215;

UPDATE public.messages SET content_feminine = $feminine_text$Sim, eu sei que sofres e sofres muito. Reconheço que não mereces esse sofrimento, mas é importante que compreendas que és tu quem te priva demasiado e te maltratas. Compreendo que não te perdoes, que haja algo no teu passado que te atormente. Hoje, liberta-te aqui, fala sobre isso, sem medo ou julgamento, e verás a tua Alma e vida renascerem das cinzas. Não te condeno, apenas amo, mas também sei que enquanto não soltares essa culpa, tudo ficará distorcido e aprisionado . Este é o grande objetivo deste ano na tua vida. Renascerás das cinzas, perdoa-te a ti mesma e recriarás a tua história, a tua vida. Tudo será novo. Estás preparada para isso?$feminine_text$ WHERE id = 312;

UPDATE public.messages SET content_feminine = $feminine_text$Que coração grande e ferido, tão ferido, mas que bela é a tua capacidade de Amar. Sei que sofres por não poderes mudar o mundo que te rodeia e sentes uma grande impotência. Faço-te um desafio: muda apenas o teu mundo e aceita o mundo dos outros e o mundo que te rodeia, e verás que a vida voltará a sorrir novamente. Não podes tornar o mundo e as pessoas melhores, a menos que essa seja a sua vontade. Mas podes ser um exemplo para elas se aprenderes a mudar em ti mesma. Muda e aí, talvez, elas aprendam ou não. O mundo é assim, imperfeito. Aceita isso, pois é a dualidade.$feminine_text$ WHERE id = 324;

UPDATE public.messages SET content_feminine = $feminine_text$Tu finges que estás bem, mas eu sei que não. Tu tens medo de estares a usar o teu Ego e de seres pouco humilde. Isso já vem de outras vidas, em que foste reduzida à insignificância pela maldade dos homens, mas agora és livre, e eu mereço que tu mereças, porque na realidade mereces. Por favor, fica ciente do que te digo: há uma vida cheia de sinónimos de amor, que foi preparada para ti, mas tu tens de aceitar que mereces e depois abrir-te para que ela chegue até ti. E um dia cá nos encontramos para festejar.$feminine_text$ WHERE id = 339;

UPDATE public.messages SET content_feminine = $feminine_text$Sabes qual é o pior de todos os males? Quando precisas da aprovação dos outros para seres quem és. Isso associado ao fenómeno do julgamento, seja em relação a ti mesma ou aos outros é a receita ideal para uma não evolução, e isso já vem para ser superado há tantas vidas. Porque é que tu não te ouves? Não acreditas em ti? Porque é que os outros te levam a ser esse "Ser" fraco, sem brilho ou com um brilho fosco? E a última pergunta que te faço é: "Tu queres mesmo mudar?". Vá, então começa...$feminine_text$ WHERE id = 341;

UPDATE public.messages SET content_feminine = $feminine_text$Corre, ganha força, pois chegou o momento de fortaleceres a tua existência, a tua jornada e a tua alma. Há muito tempo que esperávamos por ti para te recordarmos quem és e qual o verdadeiro motivo da tua partida para tão longe de nós, tão distante da tua verdadeira casa. Hoje, aqui, revelo-te que partiste para redescobrir a capacidade de te amares, mesmo estando aqui em baixo, tão distante. Foste em busca do amor perdido, do amor por ti própria. Chegou o momento de aprenderes a amar-te verdadeiramente, a respeitar-te e a reconheceres o teu único e extraordinário valor. Verás que, através desse amor próprio, finalmente encontrarás a felicidade.$feminine_text$ WHERE id = 400;

UPDATE public.messages SET content_feminine = $feminine_text$Longe daquele dia que te marcou negativamente, mas ainda hoje estão aí dentro todas as limitações, as memórias de dor, todas as batalhas, algumas perdidas, outras vencidas. Nesse teu passado criámos uma guerreira, uma força bruta da natureza, e o porquê de ter sido assim? A vida proporciona-nos formas e ferramentas para nos transformarmos em seres capazes de superar qualquer limitação, qualquer medo, pois é de Almas assim que o mundo precisa. Por isso, hoje digo-te: acabou o tempo da tua construção, guerreira. Em breve, testemunharás a recompensa pela tua luta, perseverança e dedicação. Até lá, podes começar a celebrar, pois a tua realidade mudará, tudo finalmente transformar-se-á, porque tu mereces.$feminine_text$ WHERE id = 402;

UPDATE public.messages SET content_feminine = $feminine_text$As flores possuem perfume e significados atribuídos às suas cores e à sua energia. Tu aprecias profundamente as flores e conheces a maravilhosa energia que delas emana, semelhante à que brota de ti quando te entregas de coração."Entregar" é a tua missão: entregares-te a ti mesma, assim como todas as tuas preocupações, pois existem muitas maneiras pelas quais podemos ajudar-te, trazendo-te paz e soluções para tudo o que te atormenta. Não te forces, não resistas; permite que tudo flua, deixa ir para que tudo se harmonize e possa tornar-se verdadeiramente bom. Entrega a tua vida ao céu e permanece atenta aos momentos certos para avançar. Por agora, entrega-te, e eu estarei contigo. E tudo, absolutamente tudo, será perfeito, exatamente como deveria ser, em uníssono com o universo.$feminine_text$ WHERE id = 406;

UPDATE public.messages SET content_feminine = $feminine_text$"O que é o Amor?" Questionas-te, por vezes de forma consciente, outras nem tanto. A verdade é que te ouço... E hoje, faço-te a mesma pergunta: "Há Amor dentro de ti? Amas-te a ti mesma? Respeitas-te incondicionalmente?" Acredito que, tal como eu, conheces a resposta. A partir do momento em que assumires a responsabilidade por essa falta, por tal escassez, compreendendo que o Amor começa individualmente dentro de cada um de nós, primeiro por nós mesmos e, em consequência, pelos outros e irás não só encontrar o Amor, mas, mais importante, ser o Amor. Compreendes? " Encontra-te " é a tua palavra-chave.$feminine_text$ WHERE id = 413;

UPDATE public.messages SET content_feminine = $feminine_text$Ser um "Ser" melhor exige muito trabalho, sem dúvida, devido à sua grande importância. Observo-te por vezes quase a desistir, enquanto te dedicas a aprender e a melhorar a cada dia, a cada momento. No entanto, não te concentres tanto em ser um ser perfeitamente correto, foca-te, antes de mais, em aceitar-te tal como és. Nós, assim como o universo, sabemos exatamente tudo sobre ti, ao contrário de ti própria. Quem foste? Quem vieste ser? E quem poderás vir a ser? Não te prendas ao que achas que esperamos de ti. Não te julgamos, estamos aqui apenas para te apoiar, caso desejes fazer melhorias na tua energia, no teu comportamento e, claro, na tua vida, consciente dos benefícios que isso te pode trazer. Então, avancemos juntos, com muito amor, ao teu ritmo e no teu tempo.$feminine_text$ WHERE id = 420;

UPDATE public.messages SET content_feminine = $feminine_text$Os leões são símbolos de força, persistência e, por vezes, de uma certa agressividade. Questionas-me sobre a relevância disto para ti ou para a tua mensagem, e a resposta é: tem uma grande importância. Encorajo-te a adotar a postura de um leão, a destacar-te pela tua força e grandiosa alma, estabelece limites, diz "não"e a partir de hoje, tudo será diferente, muito diferente.- "É chegada a hora de mostrar a minha capacidade de ser, a minha força que me foi roubada e com ela a autoestima, a coragem e o amor próprio. É hora de ir, saber que há mais em mim de coragem e sabedoria do que algum dia pude imaginar, e por essa razão a minha prioridade é chorar as lágrimas contidas por todos os ferimentos que o tempo, as experiências me trouxeram, seguidamente dar primazia ao meu poder interno, ao meu animal de poder, e a partir de hoje eu serei um Leão e serei a Rainha da minha vida, serei finalmente aquilo que vim para ser, e assim é, hoje e para sempre!".$feminine_text$ WHERE id = 430;

UPDATE public.messages SET content_feminine = $feminine_text$Desde a infância, procuras, sem compreender bem o motivo, por uma atenção desmedida, numa busca incessante por algo indefinido, que te impulsiona frequentemente numa direção incerta. Nesta, que é a tua corrida, confrontas-te com um vazio e uma profunda insatisfação, até que, eventualmente, a tua vida se enche de questões e o vazio começa a dominar o teu ser, o teu mundo interior. Chegou o momento de atribuir significado a esse vazio, a esse sentimento de abandono, rejeição e solidão. Este é, sem dúvida, o teu grande objetivo. Estás no limiar de um término, desde que estejas disposta a compreender e a curar. Esforça-te para que esse vazio, essa insatisfação, que ecoa de vidas passadas, se dissipe. Com a energia certa, agora tens a oportunidade de curar e libertar-te. Após resolver tudo, descobrirás que uma nova vida, de outra dimensão, começará a integrar o teu quotidiano, tornando-se parte da tua existência. Por favor, não desistas. Falta apenas um pouco, só um pouco.$feminine_text$ WHERE id = 431;

UPDATE public.messages SET content_feminine = $feminine_text$Tu, que te escondes do mundo, até de ti mesma, em algum lugar nas sombras, deixa-me dizer-te: abre-te, mostra-te ao mundo. Há tanta beleza na tua energia, tanta beleza para descobrires em ti mesma. Quando te sentires assaltada pelas lembranças do mal que já viveste nesta vida, pensa em mim, nas experiências que vivi. Nada me mudou, nada me destruiu; pelo contrário, apenas me fortaleceu. Essa mesma força e união que encontrei, pretendo trazer-ta para a tua vida. Quero mostrar-te que não és uma pessoa frustrada, mas sim alguém sensível que ainda não compreendeu totalmente o mundo. Chegou o momento de brilhares .$feminine_text$ WHERE id = 449;

UPDATE public.messages SET content_feminine = $feminine_text$A confiança move montanhas em todos os seus formatos, mas a confiança em ti mesma, essa sim, transcende todas as barreiras para alcançar novos patamares. Além de todas as normas rigidamente estabelecidas, tu és capaz, tu consegues, tu mereces. E tu desejas, e o Céu apoia-te; tu ages, e nós enviamos energia para mais e mais realizações na tua vida, para mais e mais conquistas. Portanto, ouve com atenção: não esperes mais, é hora de embarcar na jornada dos teus sonhos e brindar a humanidade com a sua realização. Então, vamos lá. Começa aqui e agora.$feminine_text$ WHERE id = 465;

UPDATE public.messages SET content_feminine = $feminine_text$Às vezes, parece que o coração não aguentará tamanhos fustigamentos. É uma sensação de estar encurralada, onde tudo parece trancar, limitar-se, e nada parece dar certo. Embora essa sensação não seja completamente verdadeira, tampouco é totalmente falsa... É chegada a hora de compreender verdadeiramente o que está acontecer. Será que o Universo não nos está a conduzir a um novo conhecimento, mais evoluído e mais adequado? Adequado a quê ou a quem, isso está por esclarecer. É tempo de aprender uma nova abordagem para lidar com as situações e dar sentido à vida. Sabemos que todo conhecimento advém de novas experiências, de novos aprendizados. Estuda, investiga sobre tudo o que te foi proposto, para que possas continuar a avançar na tua jornada de vida.$feminine_text$ WHERE id = 507;

UPDATE public.messages SET content_feminine = $feminine_text$Não dá mais, não é? Não dá mais para continuar assim, fingindo que não se sente... Não dá mais para silenciar a alma e ignorar o chamado, o grito forte que ecoa dentro do teu coração. Esse grito trouxe-te à luz da verdade, à necessidade de ser feliz. Chegou o momento de fazer aquela escolha difícil, mas muito necessária. É preciso ter consciência de que o mundo pode ter os seus motivos, mas isso não apaga, de forma alguma, os teus próprios motivos. E é neles que deves focar agora, para finalmente deixar de atrair tantas perdas como antes. É hora de parar de atrair sofrimento gratuito por te abandonares, pensando estar a agir corretamente. Hoje sabemos que nunca foi, nem nunca será assim. Só o amor é real. Sim, o amor por ti mesma, longe de crenças limitantes que te impedem de voar.$feminine_text$ WHERE id = 520;

UPDATE public.messages SET content_feminine = $feminine_text$Nunca permitas que te cortem as asas . Isso é algo que qualquer aspirante a borboleta nunca, em hipótese alguma, deve conceber, nem por instantes. Por isso, digo-te que há muitas coisas que não estão alinhadas com os teus planos e é chegada a hora de finalmente decidires enfrentar essa realidade. Não com o objetivo de destruí-la, mas sim de abandoná-la. Assim, não precisarás mais de esperar que outros decidam por ti, será a tua vez de decidir. Não te aconselho a permitir isso. Aprende de uma vez por todas a tomar decisões. E para quem? Apenas para ti mesma.$feminine_text$ WHERE id = 524;

UPDATE public.messages SET content_feminine = $feminine_text$A beleza é algo que brota de ti, mas esta beleza de que te falo está muito para além das palavras e das emoções. Refiro-me à grandeza em formato de belo, algo muito raro na condição humana, e que teimas em não valorizar. Porque te venho aqui hoje dizer que não valorizas? Porque muitas vezes te vejo recusar elogios, carinho ou qualquer forma de afeto, como se isso te tornasse vaidosa, cheia demais para ser bom ou sequer permitido por Deus. Sabes o que é isso? É uma crença, mais uma entre muitas que o ser humano teima em manter. Esse elogio, que poderia ser alimento para a tua Alma, para ela sentir que vale a pena, é secado e deixado minguar por uma crença idiota e sem fundamento.$feminine_text$ WHERE id = 532;
